### ISSUE TITLE
MariaDB install on CentOS Linux release 7.2.1511 (Core)

### ISSUE THREAD

**Issue by sbrinkerhoff** [geerlingguy/ansible-role-mysql#117]
It appears on a stock 7.2.1511 machine with all updates the following is needed to install MariaDB successfully with version 2.1.1 of this module.

- Spun Centos7 on Linode
- yum update
- Apply the following playbook

```
---
- hosts: all
  remote_user: root
  vars:
    mysql_packages:
    - mariadb
    - mariadb-server
    - mariadb-libs
    mysql_daemon: mariadb
  roles:
    - geerlingguy.mysql
```

Additionally, upon startup MariaDB was unable to touch its PID file

```
160430 20:32:14 Percona XtraDB (http://www.percona.com) 5.5.46-MariaDB-37.6 started; log sequence number 1597945
160430 20:32:14 [Note] Plugin 'FEEDBACK' is disabled.
160430 20:32:14 [Note] Server socket created on IP: '0.0.0.0'.
160430 20:32:14 [ERROR] mysqld: Can't create/write to file '/var/run/mysqld/mysqld.pid' (Errcode: 2)
160430 20:32:14 [ERROR] Can't start server: can't create PID file: No such file or directory
160430 20:32:14 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```

```
[root@li1269-11 run]# cd /var/run
[root@li1269-11 run]# mkdir mysqld
[root@li1269-11 run]# chown mysql:mysql mysqld/
[root@li1269-11 run]# service mariadb start
Redirecting to /bin/systemctl start  mariadb.service
```

```
[root@li1269-11 run]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@li1269-11 run]# rpm -qa | grep maria
mariadb-libs-5.5.47-1.el7_2.x86_64
mariadb-server-5.5.47-1.el7_2.x86_64
mariadb-5.5.47-1.el7_2.x86_64
```
