### ISSUE TITLE
Importing of sql files through playbook / config ?

### ISSUE THREAD

**Issue by MelvinLoos** [geerlingguy/ansible-role-mysql#120]
I was wondering if it would be handy to include the following inside this role or else just keep it in a separate task of mine. I am building a configurable, reusable vagrant dev box (based on drupalvm) and for a certain application I need the database structure and some fixture data to be set up before I am able to run the application. So I was thinking to import sql files to do this. Since I did not find anything in your role about it I was wondering if it would be handy to include it in this repo as it might be useful for more situations? Let me know and I will create a pull request.

**Comment by JHeimbach** [comment]
Hey,

i have a simple task in my playbook to run if I need to import my database dump

```yaml
    - name: Copy Databases to System
      copy:
        src: {{ item.name }}.sql.gz
        dest: /tmp
      with_items:
      - '{{mysql_databases}}'

    - name: Import Databases
      mysql_db:
        name: "{{ item.name }}"
        state: import
        target: /tmp/{{ item.name }}.sql.gz
      with_items:
        - '{{mysql_databases}}'
```

I have a databasedump as `sql.gz` file in my home folder (named like the database) and import all dumps if i need to.
