### ISSUE TITLE
Create error log file Error

### ISSUE THREAD

**Issue by rainercedric23** [geerlingguy/ansible-role-mysql#172]
Hi I've tried to add this ansible role in the geerlinguy/centos7 but I am having problems with regards to creating the error log file

==> default: fatal: [192.168.56.100]: FAILED! => {"changed": true, "cmd": "touch
 /var/log/mariadb/mariadb.log", "delta": "0:00:00.008450", "end": "2016-10-28 13
:52:28.216368", "failed": true, "rc": 1, "start": "2016-10-28 13:52:28.207918",
"stderr": "touch: cannot touch ‘/var/log/mariadb/mariadb.log’: No such file or d
irectory", "stdout": "", "stdout_lines": [], "warnings": ["Consider using file m
odule with state=touch rather than running touch"]}

Is there some way to fix this one? thanks.

**Comment by rvanbaalen** [comment]
That's not an error, it's a warning. Nothing critical, just a suggestion to use the file module instead of manually running the 'touch' command [here](https://github.com/geerlingguy/ansible-role-mysql/blob/05bd35c48bd42746f61d9bca956e57eb8056bc10/tasks/configure.yml#L58)

**Comment by geerlingguy** [comment]
@rvanbaalen - He's also getting an error through:

```
touch: cannot touch ‘/var/log/mariadb/mariadb.log’: No such file or directory
```

In this case, it seems like it might be permissions-related. @rainercedric23 are you running the role with `become: yes`? This role presumes it has sudo privileges.

See also the role's own tests for a canonical example that is working with CentOS 7: https://github.com/geerlingguy/ansible-role-mysql/blob/master/tests/centos-7-test.yml

**Comment by AleksNovak** [comment]
I get the same issue.
@geerlingguy can you tell me why in your `task/setup_*.yml` you call `mysql_packages`.
 
```yaml
name: Ensure MySQL packages are installed.
yum: "name={{ item }} state=installed enablerepo={{ mysql_enablerepo }}"
with_items: "{{ mysql_packages }}"
register: rh_mysql_install_packages
```

But in your vars files you called it `__mysql_packages`

```yaml
__mysql_packages:
  - mariadb
  - mariadb-server
  - mariadb-libs
  - MySQL-python
  - perl-DBD-MySQL
```

To make it work in your travis test you fixed it.
Should I push mergerequest?
Regards.

**Comment by michael-stevens** [comment]
Hi,

I'm also having trouble with this.my role setup is:

    - dev
    - { 
      role: geerlingguy.mysql,
      tags: devdb,
      mysql_packages: [ "mariadb", "mariadb-server", "mariadb-libs", "MySQL-python", "perl-DBD-MySQL" ],
      mysql_daemon: mariadb,
      mysql_log_error: /var/log/mariadb/mariadb.log,
      mysql_syslog_tag: mariadb,
      mysql_pid_file: /var/run/mariadb/mariadb.pid,
      mysql_root_password: xxxx,
      mysql_innodb_buffer_pool_size : "3096M",
      mysql_databases: [{name: xxx}],
      mysql_users: [{name: xxx, host: "xxx", password: xxx, priv: "xx.*:ALL"}]
      }

I get the same error:

    TASK [geerlingguy.mysql : Create error log file (if configured).] **************
    fatal: [864862-vm-dev.dianomi.com]: FAILED! => {"changed": true, "cmd": "touch 
    /var/log/mariadb/mariadb.log", "delta": "0:00:00.004437", "end": "2017-05-18 11:49:05.683007", "failed": 
   true, "rc": 1, "start": "2017-05-18 11:49:05.678570", "stderr": "touch: cannot touch 
   ‘/var/log/mariadb/mariadb.log’: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": 
   ["Consider using file module with state=touch rather than running touch"]}

As far as I can tell nothing is creating `/var/log/mariadb`.

**Comment by AidasK** [comment]
Has anyone found a solution?

**Comment by AleksNovak** [comment]
There is some naming issue between Mysql and MariaDB.
It is common usage to setup mariadb log files into `/var/log/` and not `/var/log/mariadb`. This playbook doesn't if the folder is created before creating the file. That’s raise an error.
You should ask something like this in you playbook:

```yaml
tasks:
  - name: Create Log folder
    file:/var/log/mysql/
      path: "{{ mysql_log | dirname }}"
      state: directory
      owner: "{{ mysql_daemon }}"
      group: "{{ mysql_daemon }}"
      mode: 0775
```

**Comment by AidasK** [comment]
Fixed by adding these vars:
```
    mysql_log_error: /var/log/mariadb.log
    mysql_enablerepo: MariaDB
``` 
and running this pretask:
```
-  name: Install the MariaDB repo.
   yum_repository:
      name: MariaDB
      baseurl: http://yum.mariadb.org/10.2/centos7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes
      description: MariaDB 10.2
- name: Create run folder
  file:
      path: /var/run/mariadb/
      state: directory
      owner: mysql
      group: mysql
      mode: 0775
```
