### ISSUE TITLE
cannot be restarted

### ISSUE THREAD

**Issue by AndreasEK** [geerlingguy/ansible-role-mysql#183]
See https://github.com/scrum-for-developers/scrum-for-developers-infra/issues/4

apparently that command seems to be run as root

**Comment by donat-b** [comment]
Root is required
https://github.com/geerlingguy/ansible-role-mysql#requirements

**Comment by geerlingguy** [comment]
@AndreasEK - Typically this role is run with `become: yes` (either on the full playbook level, or in the role line, e.g.:

```yaml
---
- hosts: database
  ...
  roles:
    - name: geerlingguy.mysql
      become: yes
```
