### ISSUE TITLE
Best way to use Percona

### ISSUE THREAD

**Issue by bvansomeren** [geerlingguy/ansible-role-mysql#19]
Hi,

First al all, thanks for making this awesome role. I'm trying to resist the urge to write my own and just use what's out there.
First of all, it's not really a bug. I got it to work.
But I am trying to understand how to go about this in the best possible way.

Percona has it's own Repo, package names and different deamon name.
Suppose my playbook is:

```
---
- hosts: all
  user: root
  vars_files:
      - vars/percona-vars.yml
      - vars/{{ansible_hostname}}.yml
  roles:
  - checks
  - geerlingguy.repo-epel
  - geerlingguy.ntp
  - geerlingguy.mysql
```

The variables that I need to override for this to work are:
```
mysql_daemon: mysql
mysql_enablerepo: "percona-release-x86_64"
mysql_packages:
  - Percona-Server-client-56
  - Percona-Server-server-56
  - MySQL-python
```
The odd thing is. If I put the mysql_daemon in vars/percona-vars.yml it would seem it gets overwritten by the value in the role. When I put it in {{ansible_hostname}}.yml it works fine.
I'm obviously doing something wrong. I'm going to assume this happens because the static file is evaluated first, then the roles and finally the dynamic vars file.

Any advice on how to do this properly?

Regards,

Barry
