### ISSUE TITLE
Operation CREATE USER failed for '********'@'%'\"

### ISSUE THREAD

**Issue by topikito** [geerlingguy/ansible-role-mysql#191]
Hi there,

I'm experiencing an issue when trying to ensure `root` access from `%`.

I have the following config as a custom var:
```yaml
mysql_users:
  - name: root
    host: "%"
    password: root
    priv: "*.*:ALL"
```

As I wan't to be able to access from wherever (this is for my local).

On first run, everything is fine:

![image](https://cloud.githubusercontent.com/assets/694244/21723162/55a370da-d427-11e6-8225-f0875592e9c7.png)

But if I re-provision: (commented out the `no_log` option)

```bash
TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
failed: [back16] (item={u'host': u'%', u'password': u'root', u'name': u'root', u'priv': u'*.*:ALL'}) => {"failed": true, "item": {"host": "%", "name": "root", "password": "root", "priv": "*.*:ALL"}, "msg": "(1396, \"Operation CREATE USER failed for '********'@'%'\")"}
```

---

May this be interfering in some way? It's obviously deleting the entry on re-provision, but I can't see why it would block it as its being executed before the user creation - and it neither works re-provisioning again.

```yaml
- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false
```

Any ideas what I can be doing wrong here?

### Environment
- Host: OSX 10.12.2
- Vagrant: 1.9.1
- VirtualBox: 5.1.12
- Ansible: 2.1.0.0
- Guest: Ubuntu 16.04 (`geerlingguy/ubuntu1604`)
- MySQL: Repository latest: 5.7.16
