### ISSUE TITLE
using password: NO on disallow root login task

### ISSUE THREAD

**Issue by ytjohn** [geerlingguy/ansible-role-mysql#212]
This is kind of like issue #89 

However, even if I destroy out the vagrant vm completely (ubuntu/trusty64) and start over I do encounter this. Removing /root/.my.cnf or changing `mysql_root_password_update: yes` to `mysql_root_password_update: no` makes no difference.

```
ansible-playbook 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

Playbook:
```
---
# To apply: `ansible-playbook -i "localhost," -c local collins.yml`
- hosts: localhost
  become: yes
  vars:
    mysql_root_password: root
    mysql_root_password_update: no
    mysql_databases:
      - name: collins
    mysql_users:
      - name: collins
        password: collins
        priv: "collins.*:ALL"
  roles:
    - role: geerlingguy.mysql
```

Results:

```
TASK [geerlingguy.mysql : Disallow root login remotely] **********************************************************************************
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.003468", "end": "2017-04-13 17:58:04.855910", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2017-04-13 17:58:04.852442", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/vagrant/collins.retry

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=23   changed=0    unreachable=0    failed=1

root@vagrant-ubuntu-trusty-64:/vagrant# cat /root/.my.cnf
[client]
user=root
password=root

root@vagrant-ubuntu-trusty-64:/vagrant# mysql -uroot -proot mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 46
Server version: 5.5.54-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

**Comment by ytjohn** [comment]
I went into the tasks and saw it was running `mysql -NBe "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"`, so I tried running that by hand and it failed the same way.  

I had been running as root after `sudo -s`. This means that my $HOME environment was still /home/vagrant.  Once I copied /root/.my.cnf to /home/vagrant/.my.cnf I was able to run the playbook. 

The trick is that we either need to be 100% logged in as the user running, `mysql_user_home`/`mysql_user_name` or set $HOME.

`sudo HOME=/root ansible-playbook -i "localhost," -c local collins.yml`

Another option would be to solve this in the playbook with either `--defaults-file` or (probably better) `--defaults-extra-file`.

```
vagrant@vagrant-ubuntu-trusty-64:/etc/ansible/roles$ sudo mysql --print-defaults
mysql would have been started with the following arguments:
--port=3306 --socket=/var/run/mysqld/mysqld.sock
vagrant@vagrant-ubuntu-trusty-64:/etc/ansible/roles$ sudo -H mysql --print-defaults
mysql would have been started with the following arguments:
--port=3306 --socket=/var/run/mysqld/mysqld.sock --user=root --password=root
vagrant@vagrant-ubuntu-trusty-64:/etc/ansible/roles$ sudo mysql --defaults-extra-file=/root/.my.cnf --print-defaults
mysql would have been started with the following arguments:
--port=3306 --socket=/var/run/mysqld/mysqld.sock --user=root --password=root
```

**Comment by geerlingguy** [comment]
I have been testing this extensively both in some test Docker containers and in my own Vagrant-based VMs, and can't get the playbook to fail (except in some situations if I already installed MySQL before running the Ansible playbook.

See, for example, this simplified test case: https://github.com/geerlingguy/ansible-role-mysql/issues/196#issuecomment-294192141

I wonder if I might be reading this issue report a little incorrectly—is the problem that your playbook fails on the first run, when MySQL is being set up? Or is the problem related to the credentials that are in use inside the VM when you're logging in as the `vagrant` user (or some other user account?).

The intention of this role is that it is run under the root account, or with `become: yes`; that way all the correct settings are configured. If it's run in a different scenario, I can't guarantee all the settings will be stored in the right places.

**Comment by ytjohn** [comment]
I did some further testing today. This is more of a sudo issue. If you start as a regular user and use sudo to run ansible-playbook, the `$HOME` variable becomes that of your regular user.

```
# To apply: `ansible-playbook -i "localhost," -c local mysql.yml`
- hosts: localhost
  become: yes
  vars:
    mysql_root_password: test
    mysql_root_password_update: yes
  roles:
    - role: geerlingguy.mysql
```

* `ansible-playbook -i "localhost," -c local mysql.yml` works. It should be noted that in an environment where sudo is not configured to be NOPASSWD, you'll get prompted for a password. 
* `sudo ansible-playbook -i "localhost," -c local mysql.yml` does not work
* `sudo HOME=/root ansible-playbook -i "localhost," -c local mysql.yml` works
* `sudo -i ansible-playbook -i "localhost," -c local mysql.yml` works (not reocmmended)
* `sudo -H ansible-playbook -i "localhost," -c local mysql.yml` works (**recommended**)

Another quicker way of testing this is just running the mysql command:

```
$ sudo mysql -NBe "SHOW DATABASES;"
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
$ sudo -H  mysql -NBe "SHOW DATABASES;"
information_schema
mysql
performance_schema
```

## quick resolution

The quickest "resolution" is just a line in the documentation for users wanting to use sudo. 

**If using sudo to run ansible-playbook, be sure to use `sudo -H` so $HOME is set correctly.**

A lot of people from the Debian/Ubuntu world use sudo (instead of being root) extensively in their tooling so that they can run the tool itself as a normal user and let the tool ask for sudo when needed. Despite the frequency this issue might pop up among people testing, I think it really only impacts those people because they're running the playbook locally, probably in a vagrant instance like me. In the normal scenario of running this against remote hosts, that will not be the case. 

## other thoughts

I thought about using the `{{ mysql_root_home }}` to eliminate the issue altogether. A change like below would remove the dependency on the $HOME variable altogether. This role already relies on `mysql_root_home` and `mysql_user_home` variables instead of facts like `ansible_user_dir` or `ansible_user_id`, so it doesn't seem like a far stretch to rely extensively on the variables passed in (either via default or as an override).  But, given the limited impact of this issue, may not be worth the effort.

```
- name: Disallow root login remotely
  command: 'mysql --defaults-extra-file="{{ mysql_root_home }}/.my.cnf" -NBe  "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false
```

**Comment by ytjohn** [comment]
Also,  I'll be happy to submit a PR either way (documentation or otherwise), but wanted to relate what I worked out this morning.  Thanks for putting out such a great role (here and elsewhere).

**Comment by geerlingguy** [comment]
@ytjohn - That makes sense. I think to make it work consistently, using `{{ mysql_root_home }}` might be the best bet. I would need to do some extra testing to ensure the role doesn't need a minor version bump because of that change, though...

**Comment by ggCS** [comment]
I'm still getting this error with no avail from the options proposed.

**Comment by ryall** [comment]
ytjohn's workaround with `-H` fixed the issue for me

**Comment by s-boardman** [comment]
Hi, I think this is the right place for this, if not I apologise in advance!

I also have this error. I don't have access to the root user on the remote server instance so I have to run as the normal user and use sudo (via become).

My playbook looks like this:

```
- name: setup mysql database on dbserver (and duplicate to appserver for backup)
  hosts: dbserver
  remote_user: svc
  become: yes
  vars_files:
    - vars/dbconfig.yml
  roles:
    # config from https://galaxy.ansible.com/geerlingguy/mysql/
    - mysql
```

vars/dbconfig.yml looks like this:

```
mysql_root_password: super_strong_password

mysql_packages:
  - mysql-server
  - mysql-client
  - libmysqlclient-dev
  - python-mysqldb

mysql_databases:
  - name: varDB
    encoding: latin1
    collation: latin1_swedish_ci

mysql_users:
  - name: svc_genetics
    host: "%"
    password: a_password
    priv: "varDB.*:ALL"
  - name: sboardman
    host: "%"
    password: anoth_password
    priv: "varDB.*:SELECT"
```

Command to run my playbook is:

```
ansible-playbook ./prod/deploy.yml --private-key=\
./ssh_keys/prod_key -K -u svc_genetics -i ./prod/hosts
```

The output I am getting from my ansible playbook is as follows:

```
TASK [mysql : Disallow root login remotely] *********************************************************
failed: [IP ADDRESS] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.004854", "end": "2017-08-01 16:00:36.466035", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2017-08-01 16:00:36.461181", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)"], "stdout": "", "stdout_lines": []}
```

I can't work out which bit is going wrong, from the above answers and issues #57 and #89 I can see that is is sudo and home related.

Any advice would be much appreciated!
