### ISSUE TITLE
Fails to install mysql57 in CentOS7

### ISSUE THREAD

**Issue by JamesYuan** [geerlingguy/ansible-role-mysql#222]
Hi,

I have tested the same environment by two different yum repo.

1. http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
2. http://repo.mysql.com/mysql57-community-release-el7-9.noarch.rpm

It seems the 1st will install the mysq56? After change the yum repo to the 2nd, the installation fails because the root password. And it doesn't repeat in the 1st scenario.

So it is an issue or need other variable to avoid the broken?

```
  pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql57-community-release-el7-9.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"
  
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server']
        mysql_log_error: ""
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
```

```
TASK [geerlingguy.mysql : Disallow root login remotely] **************************************************************************************************************************************************************************
failed: [172.16.51.140] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.006127", "end": "2017-05-10 11:39:03.874027", "failed": true, "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "rc": 1, "start": "2017-05-10 11:39:03.867900", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)"], "stdout": "", "stdout_lines": []}
```

Thanks,
James.

**Comment by JamesYuan** [comment]
Add the following task in secure-installation.yml, and it works. But don't know whether there are any flaws.

```
- name: reset mysql 5.6+ default password (no longer empty)
  shell: mysql_secret=$(sudo grep 'temporary password' {{ mysql_log_error }} | awk '{print $NF}') && mysqladmin -u root  --password=${mysql_secret} password ''
```

Thanks,
James.

**Comment by JamesYuan** [comment]
It fails when run the playbook again, :(.

**Comment by starx** [comment]
Yeah, same here with repo `https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm`

**Comment by lenada** [comment]
resetting the password to `` does not seem to be an option: 
`mysqladmin: unable to change password; error: 'Your password does not satisfy the current policy requirements'`

**Comment by dictaartisan** [comment]
I also see this problem, this time on CentOS 6.7

Here's my playbook

```
pre_tasks : 
  - name: add Mysql latest release repo
    yum: name="http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm" state=latest
    tags: rpmtest
  - name: Override variables for MySQL (RedHat).
    set_fact:
      mysql_packages: ['mysql-community-server.x86_64']
roles:
  - { role: ../../Galaxy/geerlingguy.mysql, become: yes }
```

The problem is that the initial service start launches the mysql initialization which creates a temporary root password in the log. The code doesn't pick that up.

https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html

A potential solution would be to force the '--initialize-insecure' in the init.d script - I managed to to this with this ansible code
```
  - name: ensure empty password for root at initialisation
    replace:
      path: /etc/init.d/mysqld
      regexp: '--initialize'
      replace: ' --initialize-insecure'
```
But I'm not sure if the role works well after that. I'm changing to doing things manually for now...

**Comment by alxmsl** [comment]
I've tried to use something like this for initial setup of the `5.7`
```
cat /var/log/mysqld.err | grep 'temporary password' | awk '{ print $11; }' | tail -1
```

**Comment by zgs225** [comment]
I've resolved problem by add these tasks in secure-installation.yml

``` yaml
- name: Acquire temporary root pass
  shell: >
      awk '$0 ~ "temporary password" {print $11}' {{ mysql_log_error }}
  register: mysql_root_temp_password
  when: ((mysql_install_packages | bool) or mysql_root_password_update) and ('5.7.' in mysql_cli_version.stdout)

- name: Copy .my.cnf file with temporary root password credentials
  template:
      src: "root-temporary-my.cnf.j2"
      dest: "{{ mysql_root_home }}/.my.cnf"
      owner: root
      group: root
      mode: 0600
  when: mysql_root_temp_password is defined

- name: Test temporary root password expired
  shell: "mysql -NBe 'SELECT NOW();'"
  register: mysql_temp_password_test_result
  when: mysql_root_temp_password is defined
  ignore_errors: yes

- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
      mysql -NBe 'ALTER USER "{{ mysql_root_username }}"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";' 
      --connect-expired-password
  when: mysql_temp_password_test_result is defined and 'connect-expired-password' in mysql_temp_password_test_result.stdout

- name: Overwrite .my.cnf file with root password credentials.
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: mysql_root_temp_password is defined
```

and `root-temporary-my.cnf.j2` is looks like:

``` yaml
# {{ ansible_managed }}

[client]
user="{{ mysql_root_username }}"
password="{{ mysql_root_temp_password.stdout }}"
```
