### ISSUE TITLE
Default insecure passwords seems bad

### ISSUE THREAD

**Issue by eythian** [geerlingguy/ansible-role-mysql#223]
I think that setting a default password of 'root' is dangerous. Instead, it might be worth considering:

* aborting with an error if no password is defined
* setting a large random one if none is defined

That should reduce the risk of people ending up with an insecure setup because they were in a hurry or something. Relatedly, it could be interesting to have a little aside in the docs on how to securely create a password file for when you drop this role in as a git submodule, and so want to avoid making changes to it if possible.

**Comment by geerlingguy** [comment]
> I think that setting a default password of 'root' is dangerous.

At least it's more secure than MySQL's traditional default of having no password :)

I've considered doing something like this from time to time... but it's difficult to think of a way to randomize it (where it's random on first run, then consistent on future runs), and it's also just security-through-obscurity to simply set a more secure default.

Throwing a warning if it's `root`, I might be amenable to, since it would be the least invasive and most reliable way of highlighting insecure passwords.

But one thing to keep in mind is that many people (myself included) end up using the defaults for things like one-off database environments where we need to build something quick, run some commands, then tear it down. I usually either use `'root'` or `''` (no password) for that, just because it's fast and works quickly with defaults in many of the downstream tools I use with MySQL...

**Comment by eythian** [comment]
Presumably the root password is only set if the .my.cnf exists (excluding that override option), so if a random one were generated, it would be set and written into that file the first time, and wouldn't change again?

But even a loud warning would be enough I think.

Thanks for the role btw, it's a very handy thing for me finally getting my wordpress installation ansibleised :)

**Comment by llbbl** [comment]
maybe optionally prompting for a password based on config parameter. this would not break it for people just needing an easy way to set a password and still allow for a bit more control over access to password.

**Comment by colans** [comment]
@geerlingguy wrote:
> I've considered doing something like this from time to time... but it's difficult to think of a way to randomize it (where it's random on first run, then consistent on future runs), and it's also just security-through-obscurity to simply set a more secure default.

Agreed on those points.  The solution here is to do the following:

1. Set a random password on each run (unless there's already one there and there's no reason to change it).
1. Place the generated password in `/root/.my.cnf`.

> But one thing to keep in mind is that many people (myself included) end up using the defaults for things like one-off database environments where we need to build something quick, run some commands, then tear it down. I usually either use 'root' or '' (no password) for that, just because it's fast and works quickly with defaults in many of the downstream tools I use with MySQL...

As proven time and time again, with routers and other IoT devices for example, setting passwords to common defaults is a terrible idea.

For this particular use case, you don't need to know what the password is.  It'll be in `/root/.my.cnf`, which can be accessed indirectly by running `sudo -H mysql`.  That logs you in as root, with whatever root password is in the file.  It can be used in scripts, etc.

Please have a look at [my Matomo role](https://galaxy.ansible.com/consensus/matomo) for an example of how to do this, generating a random password and then sticking it in the file.  Specifically, see [how I set the default password securely](https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-matomo/-/blob/master/defaults/main.yml#L61):

```yml
matomo_superuser_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
```

I believe that this issue should be reopened (and ideally labelled as a security issue).  I can't see a "Reopen" button so I can't do this myself.

**Comment by colans** [comment]
@geerlingguy Any chance you could roadmap this one?  Thanks.

**Comment by l3rady** [comment]
Just adding how we currently randomly change the root password on the first run of our playbook in case if it is of any use:

```
- name: install openssl to make sure we can generate a random password
  apt: name=openssl update_cache=yes cache_valid_time=3600
  tags:
    - packages

- name: make a random password for mysql root user
  shell: openssl rand -base64 48 | tr -d "=+/" | cut -c1-40
  register: mysql_root_password

- name: set mysql root password to something random if it is still set as the default
  mysql_user:
    append_privs: yes
    login_password: root
    login_user: root
    name: root
    password: "{{ mysql_root_password.stdout }}"
  ignore_errors: yes
  register: mysql_root_pw_set

- name: update root .my.cnf with new password
  ini_file:
    dest: "~/.my.cnf"
    section: client
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0600
  with_items:
    - { option: user, value: root }
    - { option: password, value: "{{ mysql_root_password.stdout }}" }
  when: mysql_root_pw_set.changed
```

This makes sure we have a random secure password setup for every new MySQL server and the password is stored in the root .my.cnf file so we can ssh in to grab the password.

I'm sure there will be a way of generating a password without the requirement of openssl but I don't know of a good way yet.
