### ISSUE TITLE
Password should not be reset to the default password each time.

### ISSUE THREAD

**Issue by solomongifford** [geerlingguy/ansible-role-mysql#24]
Currently the password is reset to the default every single time the role is run. The problem with this is that the user may have intentionally reset the password and running this role will now revert the password.  Or, in cases where the password is set by a password lookup which has since been erased locally for security reasons (our situation), the root password is regenerated.

Related to our discussion in #22, the following shell command will grab the current password.  If the result is empty, the password is not already set.  

```
cat ~/.my.cnf 2>/dev/null | grep "password=" | cut -c10-
```

I suggest using the value found above if available, otherwise use the value provided by the mysql_root_password.

**Comment by geerlingguy** [comment]
Generally, it seems best to only allow the password to be managed via configuration/Ansible, and using tools like Ansible Vault (which would allow the password to be generated during playbook run, stored in an encrypted file, then retrieved at playbook runtime) is preferred...

However, I do see a valid use case in either pulling the password from `~/.my.cnf` at runtime, or, alternatively, adding an option like `mysql_update_root_password` which would allow skipping the 'Update MySQL root password' step.

**Comment by solomongifford** [comment]
As soon as ansible 2.0 is released we'll have a better option.  An option like mysql_update_root_password  will be able to pass update_password "on_create" to toggle the behavior.

From: https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql/mysql_user.py
```
update_password:
    required: false
    default: always
    choices: ['always', 'on_create']
    version_added: "2.0"
```

**Comment by geerlingguy** [comment]
There are so many little fixes in 1.9.2 and 2.0.0 that will help with these MySQL issues... hopefully they're both out soon (2.x was slated for July), and once that happens I'll fix up these issues and get out a 2.0.x release out for this role.

**Comment by MVKozlov** [comment]
when option "mysql_root_password_update: no" selected, the /root/.my.cnf file still updated to configured(or not configured!) mysql_root_password. I find it is wrong.

I think this is must be like that:
- name: Copy .my.cnf file with root password credentials.
  when: mysql_install_packages | bool or mysql_root_password_update

**Comment by geerlingguy** [comment]
@MVKozlov - The problem is that, for many operations, the .my.cnf file _has_ to be present so this role can run certain `mysql` commands. So even if not updating the password, it has to make sure the configured password is at least present.

**Comment by MVKozlov** [comment]
Hey, I forgot other thing :)
because debian set /etc/mysq/debian.cnf by default I use in my books this task

- name: link my.cnf to root
  file: state=link src=/etc/mysql/debian.cnf path=/root/.my.cnf

...and doesn't touch debian.cnf itself. Of course it can de decorated with "when:"

**Comment by dgm** [comment]
I would like to add to that a way to read the password in the root my.cnf, and not "change" the password when it's no different than what is configured...

**Comment by solomongifford** [comment]
dgm,

We wrote an "extra_facts" module that gets this, then in our playbook we have a pre_task with:

```
---
- name: Generate mysql root passwords
  set_fact:
     mysql_root_home: /root
     mysql_root_username: root
     mysql_root_password: "{{  (root_my_cnf.password is defined) | ternary(root_my_cnf.password, lookup('password', '/tmp/passwords/' + ansible_hostname + '/mysql/root chars=ascii_letters,digits length=14')) }}"
     mysql_default_user_home: /home/other_user
     mysql_default_username: other_user
     mysql_default_password: "{{  (other_user_my_cnf.password is defined)        | ternary(other_user_my_cnf.password, lookup('password', '/tmp/passwords/' + ansible_hostname + '/mysql/other_user        chars=ascii_letters,digits length=14')) }}"
```

This essentially uses the my.cnf as the authoritative source for the password, but generates one if it doesn't exist.

I've stripped out all the other facts we get so that the example below only has the my_cnf info:
```
#!/usr/bin/python

import json
import commands
import re
import ConfigParser
import os
import socket
try:
	import dmidecode
except Exception, e:
	pass

def get_my_cnf(path):
    try: 
      my_cnf_parser = ConfigParser.ConfigParser()
      my_cnf_parser.read(path)
      my_cnf = {
        "user": my_cnf_parser.get("client", "user"),
        "password": my_cnf_parser.get("client", "password")
      }
      return my_cnf
    except Exception, e:
      return {}


def main():
    global module
    module = AnsibleModule(
        argument_spec = dict(
            virtual=dict(type='bool', default="True", required=False),
        ),
        supports_check_mode = True,
    )
   
    virtual = module.params['virtual']

    ansible_facts_dict = {
        "changed" : False,
        "ansible_facts": {
        }
    }

    try:
    	ansible_facts_dict["ansible_facts"]["root_my_cnf"] = get_my_cnf("/root/.my.cnf")
    except Exception, e:
	  pass

    try:
    	ansible_facts_dict["ansible_facts"]["other_user_my_cnf"] = get_my_cnf("/home/otheruser/.my.cnf")
    except Exception, e:
	  pass
  
    print json.dumps(ansible_facts_dict)

from ansible.module_utils.basic import *
from ansible.module_utils.facts import *
main()
```
