### ISSUE TITLE
geerlingguy.mysql module uninstallation from node

### ISSUE THREAD

**Issue by SiddharthTerse** [geerlingguy/ansible-role-mysql#247]
HI Jeff,

   I am a new user on ansible & i have installed your mysql service successfully on 10 nodes with my .yaml file 

---
 - hosts: dbservers
   sudo: yes
   roles:
    - geerlingguy.mysql

Now, due to some my mistake i want to remove / reinstall this module on 10 nodes completely. So how can i perform this task ? (Please let me know for both remove & uninstall)

Please help me on this.

**Comment by geerlingguy** [comment]
@SiddharthTerse - If you no longer want MySQL on these servers, then the best thing to do is delete the servers and rebuild them again without it.

Otherwise, you can basically undo the things this role does by adding a task like:

```yaml
  - name: Uninstall MySQL packages.
    package: name={{ item }} state=absent
    with_items:
      - mysql-server
      - mysql-client
      - etc.
```

(Putting in any packages that were installed by the role.)

I rarely include features with my roles for undoing things they do, because the whole point of automation is so you can throw away and rebuild a server the exact way you want it instead of trying to undo state changes all the time (think [cattle instead of pets](https://devops.stackexchange.com/a/654)).
