### ISSUE TITLE
Dripping tables when executing playbook

### ISSUE THREAD

**Issue by nediam** [geerlingguy/ansible-role-mysql#249]
Hello, I've installed this role for testing and I don't know is it normal or not, but each time I've executing playbook it drops my all tables:
```
TASK [geerlingguy.mysql : Ensure MySQL databases are present.] ********************************************************************************************************************************************************************************************************************
changed: [xx.xx.xx.xx] => (item={u'collation': u'utf8mb4_unicode_ci', u'name': u'test', u'encoding': u'utf8mb4'})
```

my configuration:
```
mysql_databases:
  - name: test
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
```

Any idea what can be wrong?
