### ISSUE TITLE
Installing MariaDB 10+ on CentOS 7

### ISSUE THREAD

**Issue by nathandaly** [geerlingguy/ansible-role-mysql#260]
Hi Guys,

I have tried both:

```
mysql_enablerepo: "remi"
mysql_enablerepo: "epel"
```

Both of these still install MariaDB 5.5 after a `vagrant reload --provision`.

Does anyone know how I get the latest version of MariaDB installed?

Thanks,
Nathan

**Comment by ammont** [comment]
Yes, it would be very useful to be able to install MariaDB 10.

**Comment by nathandaly** [comment]
A potential work around is to create a task that upgrades the default MariaDB install.

**Comment by sc0ttkclark** [comment]
We recently had to do this for an ansible setup, we had to add two new tasks before running DB tasks, but that got it working the way we intended. This was for Ubuntu though, but may be similar for CentOS.

```
- name: Add key for MariaDB repository
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "0xcbcb082a1bb943db"
    state: present

- name: Add repository for MariaDB
  apt_repository:
    repo: deb [arch=amd64,i386,ppc64el] http://mariadb.mirrors.ovh.net/MariaDB/repo/10.0/ubuntu trusty main
    state: present
    update_cache: yes
```

**Comment by Ranjandas** [comment]
For CentOS 7 and MariaDB 10+, just add a `pre-task` to add the appropriate yum repository.

```
- hosts: mariadb
  become: True
  pre_tasks:
    - name: Configure MariaDB Repository
      yum_repository:
        name: mariadb
        description: MariaDB
        baseurl: http://yum.mariadb.org/10.2/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: true
        state: present 
  roles:
    - role: mysql-server
```
