### ISSUE TITLE
MySQL 8.0 on Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by damianlewis** [geerlingguy/ansible-role-mysql#307]
Is it possible to install version 8.0 of MySQL on Ubuntu 16.04 and 18.04?

**Comment by meersjo** [comment]
It is, but you'll need these pre_tasks in your playbook (I'm on debian, but should be the same):

```
    - name: Install the official MySQL repo
      apt:
        deb: https://dev.mysql.com/get/mysql-apt-config_0.8.11-1_all.deb
        state: present
      when: ansible_os_family == 'Debian'
    - name: Override variables for MySQL (Debian)
      set_fact:
        mysql_packages: ['mysql-server']
      when: ansible_os_family == 'Debian'
```
Additionally, in tasks/setup-Debian.yaml, existing install is checked by existence of init.d script, but mysql 8 installs ONLY the systemd script instead. I've modified the playbook locally, but as it seems @geerlingguy isn't actually accepting pull requests, I'm not particularly bothered to push it. Here's the diff:

```
diff --git a/tasks/setup-Debian.yml b/tasks/setup-Debian.yml
index a99b44b..9bb5edb 100644
--- a/tasks/setup-Debian.yml
+++ b/tasks/setup-Debian.yml
@@ -1,11 +1,17 @@
 ---
-- name: Check if MySQL is already installed.
-  stat: path=/etc/init.d/mysql
-  register: mysql_installed
+- name: Check if MySQL init.d script is installed.
+  stat:
+    path: /etc/init.d/mysql
+  register: mysql_installed_initd
+
+- name: Check if MySQL systemd script is installed.
+  stat:
+    path: /lib/systemd/system/mysql.service
+  register: mysql_installed_systemd
 
 - name: Update apt cache if MySQL is not yet installed.
   apt: update_cache=yes
-  when: mysql_installed.stat.exists == false
+  when: mysql_installed_initd.stat.exists == false and mysql_installed_systemd.stat.exists == false
 
 - name: Determine required MySQL Python libraries.
   set_fact:
@@ -22,11 +28,11 @@
 # mysql and remove the logfiles in case the user set a custom log file size.
 - name: Ensure MySQL is stopped after initial install.
   service: "name={{ mysql_daemon }} state=stopped"
-  when: mysql_installed.stat.exists == false
+  when: mysql_installed_initd.stat.exists == false and mysql_installed_systemd.stat.exists == false
 
 - name: Delete innodb log files created by apt package after initial install.
   file: path={{ mysql_datadir }}/{{item}} state=absent
   with_items:
     - "ib_logfile0"
     - "ib_logfile1"
-  when: mysql_installed.stat.exists == false
+  when: mysql_installed_initd.stat.exists == false and mysql_installed_systemd.stat.exists == false
```
