### ISSUE TITLE
Fails during - Ensure MySQL users are present - censored problem

### ISSUE THREAD

**Issue by DuffMck** [geerlingguy/ansible-role-mysql#308]
Different from others error during the execution of __Ensure MySQL users are present__ task, this time the error is 
```
failed: [126.0.0.158] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [126.0.0.158]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

The first execution everything goes ok, the next ones are affected by this problem.

I've ran this configuration on Vagrant and an Ubuntu 18.04.
```
- hosts: default
  become: true
  roles:
    - role: geerlingguy.mysql
      vars: 
        # Root password
        mysql_root_password: root123!
        # Databases.
        mysql_databases: 
          - name: test
            collation: utf8_general_ci
            encoding: utf8
        # Users.
        mysql_users: 
          - name: " {{ mysql_app_user }}"
            host: "%"
            password: " {{ mysql_app_password }}"
            priv: "test.*:ALL"
```
