### ISSUE TITLE
Curious as to why you create two log files manually

### ISSUE THREAD

**Issue by BarbzYHOOL** [geerlingguy/ansible-role-mysql#313]
What's the point of creating two log files manually and setting their chmod?

```
- name: Set ownership on slow query log file (if configured).
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: file
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: 0640
when: mysql_slow_query_log_enabled
```
