### ISSUE TITLE
No package matching 'php5-mysql'

### ISSUE THREAD

**Issue by flaugher** [geerlingguy/ansible-role-mysql#321]
I'm trying to install MySQL using this role onto a Debian 9.8 server from a directory on a Mac running macOS 10.12.6 ("Sierra") but I get the following error and the role doesn't install:

```
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****
fatal: [cms.myproject.com]: FAILED! => {
    "changed": false
}

MSG:

No package matching 'php5-mysql' is available
```

I'm running the following Ansible playbook using ansible-playbook 2.5.3:

```
#!/usr/bin/env ansible-playbook
---
- name: Install LAMP
  hosts: lampservers
  vars:
    servername: "{{ ansible_hostname }}"
  become: true

  roles:
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php-versions }
    - { role: geerlingguy.php }
    - { role: geerlingguy.php-mysql }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.firewall }

# vim:ft=ansible
```

I've looked at the task and it installs mysql-common and mysql-server.  I looked them both up on the Debian package repository and couldn't find how they might be related to the php5-mysql package, particularly since Debian 9 is now supporting PHP 7 (or so I believe).   I tried installing php7.0-mysql and then re-running the playbook but the error still occurs so I'm not sure where this dependency is coming from.
