### ISSUE TITLE
Error when create replication user

### ISSUE THREAD

**Issue by AlexStreaming** [geerlingguy/ansible-role-mysql#324]
I'm having problems adding a replication user to my master, the error is: 

> FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'password'\n\nThe error appears to have been in '/root/.ansible/roles/geerlingguy.mysql/tasks/replication.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Ensure replication user exists on master.\n  ^ here\n"}

My vars/main.yml :

```
mysql_replication_user:
        - name: slave
          password: 012345678
          host: localhost
          priv: "*.*:REPLICATION SLAVE"
```

What is the problem?

**Comment by himura-kenshin** [comment]
TASK [geerlingguy.mysql : Ensure replication user exists on master.] ****************************************************************************************
fatal: [master]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'password'\n\nThe error appears to be in '/home/dba/.ansible/roles/geerlingguy.mysql/tasks/replication.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Ensure replication user exists on master.\n  ^ here\n"}
fatal: [slave]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'password'\n\nThe error appears to be in '/home/dba/.ansible/roles/geerlingguy.mysql/tasks/replication.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Ensure replication user exists on master.\n  ^ here\n"}

**Comment by dreamcatcha** [comment]
@AlexStreaming  did you solve the issue? I'm having the same issue

Cheers

**Comment by leitgab** [comment]
You have to set:
```yaml
mysql_replication_user:
  name: slave
  password: 012345678
  host: localhost
  priv: "*.*:REPLICATION SLAVE"
```
