### ISSUE TITLE
Failed to start mariadb service: mysql_pid_file doesn't exist

### ISSUE THREAD

**Issue by lifcn** [geerlingguy/ansible-role-mysql#332]
## My playbook 

```
[xxx@ansible playbooks]$ cat localdev.yaml 
- hosts: dbservers
  become: True
  pre_tasks:
    - name: Install MariaDB Repository
      yum_repository:
        name: mariadb
        description: MariaDB
        baseurl: http://yum.mariadb.org/10.2/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: true
        state: present
      when: ansible_distribution == "CentOS"
    - name: Override variables for MariaDB (RedHat).
      set_fact:
        mysql_packages: ['MariaDB-server', 'MariaDB-client']
        mysql_log_error: /var/log/mysql.err
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_distribution == "CentOS"
  roles:
    - role: geerlingguy.mysql
[xxx@ansible playbooks]$ 
```

> The playbook failed to start mariadb service due to missing mysql_pid_file.   
> Update as below can fix the bug

```
$ diff .ansible/roles/geerlingguy.mysql/tasks/configure.yml .ansible/roles/geerlingguy.mysql/tasks/configure.yml.orig 

54,74d53 
< - name: Create parent directory for mysql_pid_file if it does not exist 
<   file: 
<     path: "{{ mysql_pid_file.split('/')[0:-1]|join('/') }}" 
<     state: directory 
<     recurse: yes 
<     force: no 
<     owner: mysql 
<     group: mysql 
<     mode: 0755 
<     setype: mysqld_db_t 
<  
< - name: Create mysql_pid_file if it does not exist 
<   copy: 
<     content: "" 
<     dest: "{{ mysql_pid_file }}" 
<     force: no 
<     owner: mysql 
<     group: mysql 
<     mode: 0755 
<     setype: mysqld_db_t 
<  
$ 
```
