### ISSUE TITLE
Clarify running by root requirement in documentation

### ISSUE THREAD

**Issue by chuwy** [geerlingguy/ansible-role-mysql#34]
I've tried to run this role on my vagrant with following configuration:
```
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    mysql_user_home: /home/vagrant
    mysql_root_password: root
    mysql_databases:
      - name: sgt
    mysql_users:
      - name: sgt
        host: localhost
        password: verysecure
        priv: "sgt.*:ALL"
```

And ended up with following error:
```
TASK: [geerlingguy.mysql | Get list of hosts for the anonymous user.] *********
failed: [default] => {"changed": false, "cmd": ["mysql", "-NBe", "SELECT Host FROM mysql.user WHERE User = \"\""], "delta": "0:00:00.006077", "end": "2015-04-27 05:46:49.456704", "rc": 1, "start": "2015-04-27 05:46:49.450627", "stdout_lines": []}
stderr: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
````
I've spent a LOT of time trying to figure out why this happening and it appears I have to run role as root. I think it should be clear from documentation. Or may be I've done something wrong?

**Comment by nestormata** [comment]
I have the exact same issue.
Were you able to solve it?

Thanks

**Comment by chuwy** [comment]
@nestormata as I said I've changed remote_user to root and that task had completed.

**Comment by geerlingguy** [comment]
This would also be fixed by the changes listed in #36, but since that issue won't be able to be fixed for at least a few weeks, I would like to update the documentation to make this requirement a more explicit.

Another option, btw, would be to set `mysql_user_home` to `/home/vagrant`. That may work.

**Comment by geerlingguy** [comment]
Adding postponed label; will wait until a little time after Ansible 2.0.0 is released.

**Comment by sagikazarmark** [comment]
@geerlingguy no, it does not work, I've just tried.

**Comment by sagikazarmark** [comment]
@chuwy that's not an option either, you cannot connect to a vagrant box with root user.

**Comment by sagikazarmark** [comment]
I found a temporary workaround. Add this to your playbook (and leave `mysql_user_home` default value (root)):

``` yml
become_method: su
```

You can also add this post_task to copy the .my.cnf to the vagrant home directory for future usage:

``` yml
  post_tasks:
    - stat: path=/root/.my.cnf
      register: mysql_config_exists
    - shell: cp /root/.my.cnf /home/vagrant/.my.cnf && chown vagrant. /home/vagrant/.my.cnf
      when: mysql_config_exists.stat.exists
```
