### ISSUE TITLE
Python MySQL dependencies need to be updated

### ISSUE THREAD

**Issue by ergonlogic** [geerlingguy/ansible-role-mysql#344]
On a recent Ubuntu 18.04, we ran into the following fatal error:
```
TASK [geerlingguy.mysql : Remove MySQL test database.] ***************************************************************************
fatal: [test-host]: FAILED! => changed=false 
  msg: The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required.
```

**Comment by ergonlogic** [comment]
It looks like this is handled in `tasks/setup-Debian.yml`:

```yaml
- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ deb_mysql_python_package }} state=present"
```

The [`mysql_user` docs](https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html) state that:

> The below requirements are needed on the host that executes this module.
> 
> PyMySQL (Python 2.7 and Python 3.X), or
> MySQLdb (Python 2.x)

This jives with the error as reported.

I believe that the required package name for the more modern Python (2.7+) should be `python3-pymysql`.

**Comment by ergonlogic** [comment]
Actually, I misread where the error was being generated. It looks like it's the call to `mysql_db` in `tasks/secure-installation.yml`:
```yaml
- name: Remove MySQL test database.
  mysql_db: "name='test' state=absent"
```
The [requirements](https://docs.ansible.com/ansible/latest/modules/mysql_db_module.html#requirements) appear to differ slightly:
```
MySQLdb (Python 2.x)
PyMySQL (Python 2.7 and Python 3.X), or
mysql (command line binary)
mysqldump (command line binary)
```

In our case, we're running Python 2.7, but installing these packages (via `apt`) doesn't appear to resolve the issue. We're starting to suspect that Ansible is using something like `pip freeze` to determine whether these packages are installed.

**Comment by ergonlogic** [comment]
To get this running, we've so far had to upgrade to Python 3. Since Python 2.7 is EOL (on Ubuntu, at least) as of 2020, we're probably just going to have to bite the bullet and move to Python 3.

**Comment by ergonlogic** [comment]
Unfortunately, *just* updating to Python3 isn't enough... Basically, the `ansible_python_interpreter` variable doesn't appear to get set automatically.

We thought this might be due to the lookup table not having an entry for Ubuntu 18.04, but that doesn't seem to have helped:
`INTERPRETER_PYTHON_DISTRO_MAP="{'ubuntu': {'18': '/usr/bin/python3'}}" ansible-playbook ...`

**Comment by ergonlogic** [comment]
Setting `ansible_python_interpreter` if it isn't already defined, based on `ansible_fact.python.executable` works nicely:
```
- name: Set discovered Ansible Python interpreter.
  set_fact:
    ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
  when: ansible_python_interpreter is not defined
```

Unfortunately, we're hosting our code on Gitlab, so a PR is non-trivial, and I can;t upload a patch file here...

**Comment by edaemon** [comment]
@ergonlogic, can you paste the patch file as a comment here?

**Comment by ergonlogic** [comment]
Sure, here's the diff/patch from our fork on gitlab: https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-mysql/commit/852b28564e0ce76d30350a91defab2a98f5427ec.diff

**Comment by edaemon** [comment]
Thanks, that worked for me! Do you mind if I open a pull request here to apply this?

**Comment by geerlingguy** [comment]
Since this is a platform-specific, though (every platform has a different python interpreter, and it can get really hairy if my role starts overriding other python interpreters set explicitly by a playbook), I would not like to do anything that involves overriding the interpreter in here.

Rather, it would be best to ensure the environment is properly using Python 2 or Python 3 and everything is configured before this role is run (IMHO)...

**Comment by ergonlogic** [comment]
> [...] it can get really hairy if my role starts overriding other python interpreters set explicitly by a playbook [...]

FWIW, that's why we only set `ansible_python_interpreter` if it isn't already set.

An alternative would be to use `ansible_facts.python.executable` as the default in the check itself.

**Comment by schoeppe** [comment]
Why not use the python interpreter version which is currently in use by Ansible?
See this PR #350

**Comment by fildred13** [comment]
I ran into this exact same issue, running this role against 18.04, but the strange part is that by simply running the playbook a second time, the error goes away, and the task succeeds. Is this consistent with what others are seeing?

First run:

```
TASK [mysql : Remove MySQL test database.] *************************************
fatal: [glynt_api]: FAILED! => {"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
```

Second Run: 

```
TASK [mysql : Remove MySQL test database.] *************************************
ok: [glynt_api]
```

My playbooks have no `ansible_python_interpreter` setting of any kind, if that helps.

**Comment by schoeppe** [comment]
Yes, same for me.

I think this behaviour is caused by [Ansible Interpreter Discovery](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html) in combination with package manager dependencies.

I could reproduce such a behaviour on some Ubuntu 18.04 systems with pre-installed Python 3:
- In the first run Ansible is executed using Python 3. The playbook installs the dependency python-mysqldb which itself depends on Python 2.7. This changes the default Python interpreter on the target system.
- In the second run Ansible is executed using Python 2.7, the playbook uses the previously installed Python module for MySQL and everything is fine.

With my PR #350 you'll stick with the Python 3 interpreter in such cases.

**Comment by niccolox** [comment]
this issue is currently breaking Ubuntu 18 use of the role

@ergonlogic patch worked for me on Vultr

**Comment by jonpugh** [comment]
Jeff is right. Configuring settings used by the ansible runner inside the playbook is going to cause confusion and stability. It's important to keep separation, it gets very confusing.

I have resolved this by including the variable in the playbook.

Here's an example based on the README.md example:

```
- hosts: db-servers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.mysql }

  vars: 
    ansible_python_interpreter: python3
```

Here's the playbook we use to create the `devshop/server` container based on Ubuntu 18:
https://github.com/opendevshop/devshop/blob/1.x/docker/playbook.server.yml#L29

```
---
- hosts: all
  become: yes

  vars:
...
    ansible_python_interpreter: python3

  roles:
    - opendevshop.users
    - opendevshop.apache
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
```

**Comment by jonpugh** [comment]
You could also add @ergonlogic's task to pre_tasks in your playbook:

```
- hosts: db-servers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.mysql }
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined
```

**Comment by jonpugh** [comment]
To be clear: I'm not thrilled that we need a playbook variable by default for ubuntu 18. I'm just saying messing with that variable inside the Role playbook isn't a viable solution.

The hosts always have some setup involved. We were using geerlingguy/docker-ubuntu1804-ansible image, but when we discovered this, we created our own Dockerfile to use Python3 instead: https://github.com/opendevshop/devshop/blob/1.x/Dockerfile

**Comment by jfoliveira** [comment]
@geerlingguy I think the real issue is **As the role checks for the value of `ansible_python_interpreter`, how to ensure the `ansible_python_interpreter` variable is properly set?**

In my case `ansible.cfg` file has:
```
interpreter_python=/usr/bin/python3
```

1. That's enough to tell ansible that I'm using Python3, as it can be verified by debugging `hostvars` and checking the values of `ansible_python*` facts;
2. Nonetheless, this role is still installing python2 packages as the check for `python3` relies on the `ansible_python_interpreter` variable which is not automatically set when `interpreter_python` is set on the `ansible.cfg` file.

As a workaround one can add an extra var to the playbook execution parameters, just to satisfy the needs of this role's expected variable:
```
ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python3'
```
This works, but creates a long term maintainability issue to always ensure that `ansible_python_interpreter` variable and `ansible.cfg`/ `interpreter_python` are always in sync.

**My suggestion:**
It seems to me this role should not rely on `ansible_python_interpreter` variable.
Instead of testing the value of `ansible_python_interpreter` use some of the standard python related facts:

- `ansible_python_version`
or
- `ansible_python.version.major`

Any thoughts?

**Comment by pmauduit** [comment]
I encountered the same issue with a target host under debian 10, I used the following pre_task to fix it (I already had the ansible_python_interpreter variable set to python3):

```yaml
  pre_tasks:
    - name: installing python-3 mysql libraries
      apt: name=python3-mysqldb state=present
   roles:
     - role: geerlingguy.mysql
```

I saw that a step defined in the role was supposed to install the package, but it appears that it was not the right one or so, because I first apt-got it by hand.
