### ISSUE TITLE
Undefined variable __mysql_packages

### ISSUE THREAD

**Issue by YOUR1** [geerlingguy/ansible-role-mysql#348]
**OS**: Fresh installation of Ubuntu 18.04
**Role Version**: Tested on 2.9.4 and 2.9.5
**Software versions**: Python 2.7.15+, Galaxy: 2.8.2, Ansible 2.8.2
**Playbook**
```
---
- name: "Installs the MySQL server"
  hosts: dbservers
  vars:
    mysql_root_password: "{{ database_adminuserpw }}"
    mysql_root_username: "{{ database_adminuser }}"
    mysql_root_password_update: true
    mysql_enabled_on_startup: true
    mysql_databases:
      - { name: "{{ database_name }}", state: present }
    mysql_users:
      - { name: "{{ database_user }}", password: "{{ database_userpw }}", priv: "{{ database_name }}.*:ALL" }

  roles:
    - role: geerlingguy.mysql
      become: yes
```
**Message**
```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '__mysql_packages' is undefined\n\nThe error appears to have been in '/home/rbr/.ansible/roles/geerlingguy.mysql/tasks/variables.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Define mysql_packages.\n  ^ here\n"}
```
