### ISSUE TITLE
Debian 10: settings overwritten by system file

### ISSUE THREAD

**Issue by simonspa** [geerlingguy/ansible-role-mysql#360]
I am trying to use this role to configure a Debian 10 system but have found out that several of the settings are overwritten by the file located in `/etc/mysql/mariadb.conf.d/50-server.cnf`, e.g. the `datadir`.

This is problematic because I can't simply remove the file - it's not there before MariaDB is installed - and after the role it's too late because everything ended up in `/var/lib/mysql` already.

Same thing happens for `user`, `socket` etc but also `collation-server` and `character-set-server` - essentially this makes this role unusable.

Does anyone have a solution for me?

**Comment by stefanux** [comment]
are you sure? /etc/mysql/my.cnf seems to have precedence (tested innodb_buffer_pool_size and bind-address).

used packages default-mysql-server and default-mysql-server-core in my playbook):

```
  pre_tasks:
    - name: Set packages Names on Debian buster
      set_fact:
        mysql_packages:
          - default-mysql-server
          - default-mysql-server-core
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_release == 'buster'
```
