### ISSUE TITLE
Task "Check slave replication status" fails

### ISSUE THREAD

**Issue by aniro** [geerlingguy/ansible-role-mysql#375]
One of the latest updates introduced
```
login_user: "{{ mysql_replication_user.name }}"
login_password: "{{ mysql_replication_user.password }}"
```
in the following task:
```
- name: Check slave replication status.
  mysql_replication:
    mode: getslave
    login_user: "{{ mysql_replication_user.name }}"
    login_password: "{{ mysql_replication_user.password }}"
  ignore_errors: true
  register: slave
  when:
    - mysql_replication_role == 'slave'
    - mysql_replication_master | default(false)
  tags: ['skip_ansible_galaxy']
```
On a fresh installation `replication` user is created on master before replication is enabled. So it is not replicated to slave which causes login to slave using this user to fail.
