### ISSUE TITLE
RHEL8/CentOS8 installation need python2 yum plugin

### ISSUE THREAD

**Issue by SwitchTracker** [geerlingguy/ansible-role-mysql#376]
When trying default role installation on Centos8, ansible complains on python2 yum module:

```
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] **********************************************************************************************
fatal: [mysqlhost]: FAILED! => {
    "changed": false
}

MSG:

python2 yum module is needed for this  module
```
After changing module _yum_ to _dnf_ in **tasks/setup-RedHat.yml**:
```
---
- name: Ensure MySQL packages are installed.
  dnf:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
```
it works well.

So there is an consideration using DNF module for ansible when using RHEL8 with default Python3 installed.
