### ISSUE TITLE
Includes files not being updated

### ISSUE THREAD

**Issue by JuddTracy-DAS** [geerlingguy/ansible-role-mysql#392]
I have configuration options being defined like:

```
mysql_config_include_files:
  - src: 'files/mysql/stig.cnf'
```

But when I modify the file the role will not perform the update.

```
ok: [centos7-mysql] => (item={'src': 'files/mysql/stig.cnf'}) => changed=false 
  ansible_loop_var: item
  dest: /etc/my.cnf.d/stig.cnf
  invocation:
    dest: /etc/my.cnf.d/stig.cnf
    follow: false
    force: false
    group: root
    mode: 420
    module_args:
      dest: /etc/my.cnf.d/stig.cnf
      follow: false
      force: false
      group: root
      mode: 420
      owner: root
      src: /home/ansible/.ansible/tmp/ansible-local-10885f9ibfzx3/tmppe4ksqib/stig.cnf
    owner: root
    src: /home/ansible/.ansible/tmp/ansible-local-10885f9ibfzx3/tmppe4ksqib/stig.cnf
  item:
    src: files/mysql/stig.cnf
  src: /home/ansible/.ansible/tmp/ansible-local-10885f9ibfzx3/tmppe4ksqib/stig.cnf
```

Not sure why this is not working.  Also I don't want to force the update since it will always restart mysql on every run.
