### ISSUE TITLE
mysql_replication_master variable is always evaluating to 'false'

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-mysql#401]
...at least in my example in Ansible for DevOps: https://github.com/geerlingguy/ansible-for-devops/issues/229

I've been trying to see why replication steps are being skipped when I have the following variables:

```yaml
mysql_replication_role: master
mysql_replication_master: 104.131.38.165
mysql_replication_user:
  name: replication
  password: secret
```
