### ISSUE TITLE
Unable to connect to remove the test database even if everything else is fine

### ISSUE THREAD

**Issue by jacquesbh** [geerlingguy/ansible-role-mysql#412]
Hi!

I'm pretty sure it's an environment related issue, but still have no clue to where it comes from.
I'm running my playbook against some dummy servers and it works well.

But when I run it on an AWS Debian Stretch machine I get this issue:
```
unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials
```

<details><summary>See the full trace</summary>
```
The full traceback is:
  File "/tmp/ansible_mysql_db_payload_zzhj68z1/ansible_mysql_db_payload.zip/ansible/modules/database/mysql/mysql_db.py", line 383, in main
  File "/tmp/ansible_mysql_db_payload_zzhj68z1/ansible_mysql_db_payload.zip/ansible/module_utils/mysql.py", line 81, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 588, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 853, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
fatal: [bpi.pre-image]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "collation": "",
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encoding": "",
            "ignore_tables": [],
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "name": [
                "test"
            ],
            "quick": true,
            "single_transaction": false,
            "state": "absent",
            "target": null
        }
    },
    "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, \"Access denied for user 'root'@'localhost'\")"
}
```
</details>

I've included the playbook like this: `{ name: geerlingguy.mysql, become: yes }`.
Everything runs well except this task.

I've tried to connect on the server to the mysql using the password setup in `mysql_root_password`: it works well.
At least it works for `localhost`, not for `127.0.0.1`.
So the password is correct.

The `/root/.my.cnf` is correct too, it contains the user and the password in the `client` section.

So basically I've added an `ignore_errors: yes` to the task right now. The `test` database isn't present anyway.

But what I don't understand is: the full setup went well except this task. It installed MySQL, it did all the setup and boom…

The machine:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

Packages (mariadb and mysql):
```
libmariadbclient18/oldstable,now 10.1.45-0+deb9u1 amd64 [installed,automatic]
mariadb-client-10.1/oldstable,now 10.1.45-0+deb9u1 amd64 [installed,automatic]
mariadb-client-core-10.1/oldstable,now 10.1.45-0+deb9u1 amd64 [installed,automatic]
mariadb-common/oldstable,now 10.1.45-0+deb9u1 all [installed]
mariadb-server-10.1/oldstable,now 10.1.45-0+deb9u1 amd64 [installed,automatic]
mariadb-server-core-10.1/oldstable,now 10.1.45-0+deb9u1 amd64 [installed,automatic]
default-mysql-server/oldstable,now 1.0.2 all [installed,automatic]
libdbd-mysql-perl/oldstable,now 4.041-2 amd64 [installed,automatic]
mysql-common/oldstable,now 5.8+1.0.2 all [installed]
mysql-server/oldstable,now 5.5.9999+default amd64 [installed]
php7.3-mysql/unknown,now 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72 amd64 [installed]
python3-mysqldb/oldstable,now 1.3.7-1.1 amd64 [installed]
```

When I see this actually I'm thinking of a conflict issue? Seems strange since the machine was clear new before.

**Comment by nhedger** [comment]
Hi, I've experienced the same issue on Debian 10.

It seems that MySQL/MariaDB service needs to be restarted for the credentials in `/root/.my.cnf` to be taken into account by the `mysql_db` module.

To put this theory to the test, I've added the following lines to **tasks/secure-installation.yml**, right before the last task:

```yaml
- name: Restart MySQL service
  service: 
    name: "{{ mysql_daemon }}"
    state: restarted 
    sleep: 5
```

Since then, I've had no problem running this role.

**Comment by patacra** [comment]
I also noticed the same issue on Debian 10 and also tried the "restart" option which works fine.

But I then thought about another option: **flush the privileges after the password modification!**
And it works fine. It's probably more efficient and a bit cleaner since the server will be restarted later in the handlers after all the tasks (of course to late to solve the problem).

We could add the `FLUSH PRIVILEGES;` in each SQL query, like this, in **tasks/secure-installation.yml**:

```yaml
# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
    mysql -u root -NBe
    'ALTER USER "{{ mysql_root_username }}"@"{{ item }}"
    IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}"; FLUSH PRIVILEGES;'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: >
    ((mysql_install_packages | bool) or mysql_root_password_update)
    and ('5.7.' in mysql_cli_version.stdout or '8.0.' in mysql_cli_version.stdout)

# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  shell: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}"); FLUSH PRIVILEGES;'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: >
    ((mysql_install_packages | bool) or mysql_root_password_update)
    and ('5.7.' not in mysql_cli_version.stdout and '8.0.' not in mysql_cli_version.stdout)
```

Or add another task after these 2 just to do that. The first option will certainly be faster than re-lauching a shell and a connection to the DB.
