### ISSUE TITLE
Error during install , "python mysqldb module is required"

### ISSUE THREAD

**Issue by efreedom79** [geerlingguy/ansible-role-mysql#42]
I was reading the post at https://servercheck.in/blog/using-ansible-galaxy to set up my lamp install.

When running ansible, I get this error:

TASK: [../galaxy-roles/geerlingguy.mysql | Update MySQL root password for localhost root account.] ***
failed: [ec2-23-22-178-120.compute-1.amazonaws.com] => (item=ip-10-69-147-104) => {"failed": true, "item": "ip-10-69-147-104"}
msg: the python mysqldb module is required
failed: [ec2-23-22-178-120.compute-1.amazonaws.com] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
msg: the python mysqldb module is required
failed: [ec2-23-22-178-120.compute-1.amazonaws.com] => (item=::1) => {"failed": true, "item": "::1"}
msg: the python mysqldb module is required
failed: [ec2-23-22-178-120.compute-1.amazonaws.com] => (item=localhost) => {"failed": true, "item": "localhost"}
msg: the python mysqldb module is required

I checked for the mysqldb module by running python and typing "import mySQLdb" and there were no errors so everything does appear to be installed. I did go to several sites to see how to install the module and I believe everything is in place.

I'm using python 2.7 running on the current default Amazon Linux for ec2.

**Comment by geerlingguy** [comment]
I haven't seen this issue on any of the servers I manage, so I wonder if it's something unique about the Amazon Linux AMIs/setup... Can you make sure the `sudo` user is able to `import mySQLdb` as well? Maybe it's only installed in a Python environment accessible to your normal user.

**Comment by timani** [comment]
I was receiving the same error using `sudo` in my playbook. 

You can run `sudo pip show MySQL-python` to see if the python mysqldb module is loaded for the user. 

There were two ways to fix it. 

#### 1. Installing python mysqldb module with pip

```shell
# Install the python mysqldb module
$ sudo pip install MySQL-python
# Verify python mysqldb module is installed
$ sudo pip show MySQL-python
---
Metadata-Version: 1.1
Name: MySQL-python
Version: 1.2.5
Summary: Python interface to MySQL
Home-page: https://github.com/farcepest/MySQLdb1
Author: Andy Dustman
Author-email: farcepest@gmail.com
License: GPL
Location: /usr/lib64/python2.7/site-packages
Requires: 
```

#### 2. Add the mysqldb module in a playbook

It could be easier to install the python module within your playbook

```yaml
---
# tasks file for mysql
  - name: Install the Python MySQLB module
    pip: name=MySQL-python

  - name: Create the flask database
    mysql_db: name=flask_db state=present
```

With each fix the playbook ran correctly
```
$ ansible-playbook ansible/site.yml -c local --ask-sudo-pass

PLAY [localhost] ************************************************************** 

TASK: [common | Database volume container] ************************************ 
ok: [localhost]

TASK: [mysql | Install the Python MySQLB module] ****************************** 
ok: [localhost]

TASK: [mysql | Create the Drupal database] ************************************ 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

**Comment by andycutright** [comment]
For Trusty, running in AWS

- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
  become: yes
  become_method: sudo

**Comment by jhogendorn** [comment]
For those like me whom end up here via the almighty google, if you're on Centos or anything Centos-like (Amazon Linux for example), the reason MySQL-python is failing for you is because its been made into two packages, MySQL-python26 and MySQL-python27.

**Comment by geerlingguy** [comment]
Ugh, Amazon Linux again... why do they have to do everything _ever so slightly different_ than RHEL/CentOS?

Going to close this as there's a definite solution now—make sure the proper MySQL python package is installed before this role is run.

**Comment by kmoll** [comment]
I ran into this using DrupalVM playbook directly to another server running a plain vanilla version of ubunut-16.04 (not Jeffs box).  This uses python3 instead of python2 (2.7).  You can allow most of the playbook to run by using 'ansible_python_interpreter=/usr/bin/python3' in the inventory file in examples/prod.  I get this error still.  I try to manually install python_mysqldb but it says its installed and the latest version.  Not sure why the mysql_db command in ansible can't find the right package.  Seems like this is a bug with Ansible and Python3, not DrupalVM.

I got around it by creating a task to make sure python2 was installed and there was a symlink created:
```    - name: Install python 2.7
      apt:
        name: python2.7
        state: present
        update_cache: yes

    - name: create python symlink
      file:
        src: /usr/bin/python2.7
        dest: /usr/bin/python
        owner: root
        group: root
        state: link
```

According to the docs, at http://docs.drupalvm.com/en/latest/other/production.  You run the init.yml file in the production example folder first.  This is where I put this task, and in the command line I add the ansible_python_interpreter command:

```
ansible-playbook -i examples/prod/inventory examples/prod/bootstrap/init.yml -e 'ansible_python_interpreter=/usr/bin/python3'
```

This will then run and make sure python2 is install, then you can run the command without specifying the interpreter with the playbook.yml file and it will work:
```
ansible-playbook -i examples/prod/inventory provisioning/playbook.yml --sudo --ask-sudo-pass
```

**Comment by kmoll** [comment]
I checked the box `geerlingguy/ubuntu1604` and this already had python2.7 along side python3.5 so I didn't run into the issue there.

**Comment by dirkaholic** [comment]
Just ran into this as well and the solution that works for me on Ubuntu 14.04 as well as on 16.04 is:

```
- name: Install packages required for ansible mysql modules
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
  when: ansible_lsb.major_release|int < 16

- name: Install packages required for ansible mysql modules
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - libmysqlclient-dev
  when: ansible_lsb.major_release|int >= 16

- name: Install Python package manager
  apt: name=python3-pip state=present
  when: ansible_lsb.major_release|int >= 16

- name: Install the Python package required for ansible MySQL modules
  pip: name=mysqlclient
  when: ansible_lsb.major_release|int >= 16
```

**Comment by cstavaru** [comment]
Actually, this is not fixed and it's a real issue on Amazon Linux. Installing MySQL-python with pip will fail because a file (my_config.h) which is actually installed by the geerlingguy.mysql role, will be missing. Package python-devel must also be installed beforehand.

I think the true solution is supporting Amazon Linux as a first-class citizen (with its own configuration and list of packages to install).

**Comment by gwagroves** [comment]
Ubuntu 16.04. The following worked for me:

```yml
vars:
  ansible_python_interpreter: /usr/bin/python3
tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - python3-pip
      - python3-mysqldb
```

**Comment by mglaman** [comment]
Ran into this on DigitalOcean, all of my droplets are 16.04

Inventory file

```
[forkdin:vars]
ansible_ssh_user=XXXXXXX
deploy_target=XXXXXXX
ansible_python_interpreter=/usr/bin/python3
```

Database playbook

```
---
- hosts: database
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Ensure dependencies are installed.
      apt: name={{ item }} state=present
      with_items:
        - python3-mysqldb

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }

  tags:
    - database
```
