### ISSUE TITLE
How should "when" rules in replication.yml work?

### ISSUE THREAD

**Issue by 171koinoyokan171** [geerlingguy/ansible-role-mysql#466]
Hello!

I have installed single instance mysql server before. But know I need to make master-slave replication. I have defined 

For slave:
```
mysql_server_id: "2"
mysql_replication_role: 'slave'
```

For master:
```
mysql_server_id: "1"
mysql_replication_role: 'master'
```

For both (group_vars):
```
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"
mysql_expire_logs_days: "10"
mysql_replication_master: '10.1.0.1' # master server ip, accessible from slave
mysql_replication_user:
    name: replication
    password: "{{ mysql_user_replication_password }}"
mysql_users:
  - name: replication
    host: '%'
    password: "{{ mysql_user_replication_password }}"
    priv: "*.*:RELOAD,PROCESS,REPLICATION SLAVE,REPLICATION CLIENT"
```

Problem started at this line:
https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/replication.yml#L21

Slave var was registered and field "Is_Slave" was true (checked with debug).

All of next jobs in replication.yml were skipped because of this rule:
https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/replication.yml#L32

`(slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave is failed)`

Please, help me to understand how should first part of this condition work - how it could be defined for slave and be false for field "Is_Slave".

P.S. Checked with debug that mysql_replication_user, mysql_replication_master, mysql_replication_master are present.
