### ISSUE TITLE
Industrialize deployment

### ISSUE THREAD

**Issue by denics** [geerlingguy/ansible-role-mysql#468]
I @geerlingguy and thanks for all your ansible roles. they are very helpful. 

I am now using your roles on a drupal farm and I was wondering like this:

- I declare my sites in a vocabulary called drupal_websites, one for each site in the farm:
    ```yaml
    drupal_websites:
  # www.my.site
  - {
      url: 'www.my.site',
      devurl: 'www.dev.my.site',
      name: 'www.my.site',
      alias: '',
      mysql_user: '{{ secret_drupal_mysite_mysql_user }}',
      mysql_password: '{{ secret_drupal_mysite_mysql_password }}',
      mysql_database: '{{ secret_drupal_mysite_mysql_database }}'
      masked: false
    }
    ```
- Looping through the vocabulary I create a vhost using a template (working, happy with it, thanks!) geerlingguy/apache geerlingguy/php-fpm:
    ```j2
    Alias "{{ item.alias }}" "/home/vhosts/{{ item.name }}/www"
    <Directory "/home/vhosts/{{ item.name }}/www/">
     Options FollowSymLinks Multiviews
     AllowOverride All
     {% if item.masked %}
       AuthType Basic
       AuthName "CIAO!"
       AuthUserFile "{{ apache_auth_user_file }}"
       Require valid-user
     {% else %}
        Require all granted
     {% endif %}
    </Directory>
    ProxyPassMatch ^(.*){{ item.alias }}/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/home/vhosts/{{ item.name }}/www/$2$3"
    ```
- Looping through the vocabulary I would like, in the same way, create my dbs. At the moment I have a very long list of like this that I have to fill at each website by hand:
    ```yaml
    mysql_databases:
    # site1
    - name: "{{ secret_drupal_site1_mysql_database }}"
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
    # site2
    - name: '{{ secret_drupal_site2_mysql_database }}'
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
    # site40
    - name: '{{ secret_drupal_site2_mysql_database }}'
      encoding: utf8mb4
      collation: utf8mb4_unicode_ci
    mysql_users:
    # site1
    - name: "{{  secret_drupal_site1_mysql_user }}" 
      host: "%"
      password: '{{ secret_drupal_site1_mysql_password }}' 
      priv: "{{ secret_drupal_site1_mysql_database }}.*:ALL"
    # site2
    - name: "{{  secret_drupal_site2_mysql_user }}" 
      host: "%"
      password: '{{ secret_drupal_site2_mysql_password }}' 
      priv: "{{ secret_drupal_site2_mysql_database }}.*:ALL"
    # site40
    - name: "{{  secret_drupal_site40_mysql_user }}" 
      host: "%"
      password: '{{ secret_drupal_site40_mysql_password }}' 
      priv: "{{ secret_drupal_site40_mysql_database }}.*:ALL"
    ```

I would like to know if there is a way to automatically generate mysql db and users like I do with apache. Looking at your code I do not think it is possible.

Thanks for your help!
