### ISSUE TITLE
missing Debian 11 vars

### ISSUE THREAD

**Issue by crazychatting** [geerlingguy/ansible-role-mysql#469]
like defined in _tasks/variables.yml_ in line 7:
```
---
# Variable configuration.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
```
the variables will be used for the major distibution version first, but in the vars directory there is only _Debian.yml_ and _Debian-10.yml_.
The definitions for Debian-11 are missing. So the task "Ensure MySQL packages are installed" is failing with:
`FAILED! => {"changed": false, "msg": "No package matching 'mysql-server' is available"}`

My workaround for this is at the moment to create a symlink to the _Debian-10.yml_ with:
`ln -s Debian-10.yml Debian-11.yml`
