### ISSUE TITLE
should this work with mysql 5.7?

### ISSUE THREAD

**Issue by jgainey** [geerlingguy/ansible-role-mysql#484]
I'm trying to install mysql5.7 from the community repo.  everything seems to go fine until it tries to access the mysql database with the mysql command line client

TASK [mysql : Disallow root login remotely] *************************************************************************************************************************************************************************************************
failed: [css-mfgweb1-t7.cookgroup.nao] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"ansible_loop_var": "item", "changed": false, "cmd": ["mysql", "-NBe", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.012698", "end": "2022-03-18 13:32:49.616623", "item": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "msg": "non-zero return code", "rc": 1, "start": "2022-03-18 13:32:49.603925", "stderr": "ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)", "stderr_lines": ["ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)"], "stdout": "", "stdout_lines": []}

i looked through the code it seems like it should need to:
1.  get the default installation root password from the error log
2.  specify the default installation root password on the command line until it resets the root password

here's the snippet from the log with the randomly generated temporary password:

2022-03-18T17:32:45.659519Z 1 [Note] A temporary password is generated for root@localhost: 0,h0pQfs7J8l

i'm not familiar with new versions of mysql and whether this is the same or not.

**Comment by gh0st** [comment]
I find I'm running into the same issue. Originally maybe it seemed as though a mysql install left the root password empty as ''. Or perhaps that the install was not performed with some package manager like yum for example on RHEL. But using yum on RHEL7 to install mysql from the rpm files it does as @jgainey describes. The default installation password is written to `/var/log/mysqld.log`. I can scrape that and write it to a var in ansible but this still doesn't seem to yield results and fails. I've tested this and found it true for mysql 5.7 and 8.0.

**Comment by unleftie** [comment]
here is my solution

```
- name: Get temporary root password from logs
  shell: cat {{ mysql_log_error }} | grep "temporary password" | grep -oE '[^ ]+$'
  args:
    executable: /bin/bash
  register: _mysql_temporary_root_password

- name: Detect my.cnf file
  stat:
    path: /root/.my.cnf
  register: _mysql_root_conf_file_check

- name: Update MySQL root password from temporary password
  mysql_user:
    login_unix_socket: "{{ mysql_socket }}"
    login_user: root
    login_password: "{{ _mysql_temporary_root_password.stdout }}"
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    state: present
  when: _mysql_root_conf_file_check.stat.exists
  no_log: true

- name: Update MySQL root password from temporary password
  shell: mysql -NBe "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';" --connect-expired-password --user='{{ mysql_root_username }}' --password='{{ _mysql_temporary_root_password.stdout }}'
  args:
    executable: /bin/bash
  when: not _mysql_root_conf_file_check.stat.exists
  no_log: true

# Has to be after the password assignment, for idempotency
- name: Copy my.cnf file with root password credentials
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
  when: mysql_install_packages | bool or mysql_root_password_update
```
