### ISSUE TITLE
Change mysql_bind_address: '0.0.0.0' to mysql_bind_address: '127.0.0.1' in defaults

### ISSUE THREAD

**Issue by lukasfischer** [geerlingguy/ansible-role-mysql#502]
It's not a bug, but a potential security issue:

Change mysql_bind_address: '0.0.0.0' to mysql_bind_address: '127.0.0.1' in defaults for better security. I do think that exposing mysql to the public should be a conscious decision.

In addition, you may want to change in the examples doc:
```
mysql_users:
  - name: example_user
    host: "%"
    password: similarly-secure-password
    priv: "example_db.*:ALL"
```

to 
```
mysql_users:
  - name: example_user
    host: "**localhost**"
    password: similarly-secure-password
    priv: "example_db.*:ALL"
```

Or add a second example.
