### ISSUE TITLE
FAILED! => {"changed": false, "msg": "Could not find the requested service mysql: host"}

### ISSUE THREAD

**Issue by garyyang6** [geerlingguy/ansible-role-mysql#521]
Per https://galaxy.ansible.com/geerlingguy/mysql, I installed the role,

ansible-galaxy install geerlingguy.mysql

playbooks/install_database.yaml:
```
- hosts: database
  user: ubuntu
  become: yes
  vars_files:
   - ../vars/database.yaml
  roles:
    - role: geerlingguy.mysql
```
vars/database.yaml
```
mysql_databases:
  - name: db01
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
mysql_users:
  - name: linuxhint
    host: "%"
    password: secret
    priv: "db01.*:ALL"
```
Ran the check command, 

ansible-playbook -i hosts playbooks/install_database.yaml -e ansible_python_interpreter=/usr/bin/python3 --check

I got the error,

```
fatal: [30.10.1.7]: FAILED! => {"changed": false, "msg": "Could not find the requested service mysql: host"}
30.10.1.7                  : ok=18   changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```
