### ISSUE TITLE
Mysql role failing with empty hostname error

### ISSUE THREAD

**Issue by Manju-1195** [geerlingguy/ansible-role-mysql#539]
Hi, 

I'm trying to install latest version of mysql on an ubuntu machine(Version 22.04) using geerlingguy.mysql role.
However the role fails with below error

```
TASK [geerlingguy.mysql : Check master replication status.] *********************************************************************************************************************************************************
fatal: [ix-field.interaxo.dev -> {{ mysql_replication_master_inventory_host }}]: FAILED! => {"msg": "Empty hostname produced from delegate_to: \"{{ mysql_replication_master_inventory_host }}\""}
```
Below is the variable file that's defined.
```
mysql_databases:
  - name: "{{ database }}"
    state: present
mysql_users:
  - name: "{{ name }}"
    password: "{{ password }}"
    priv: "{{ name }}.*:ALL"
    state: present
```
I've not enabled replication, so not sure why the variable `mysql_replication_master_inventory_host ` is checked.
Any input here will be really helpful.

Thanks!
