### ISSUE TITLE
Separate APT and YUM package list variable

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-mysql#56]
Currently there is only one variable for packages: `mysql_packages`.

In case you want to use a playbook on both Debian and RedHat with extra packages, you can only define them for either Debian or Readhat. By using a separate variable, you can define both.

**Comment by geerlingguy** [comment]
Currently, the role is intended for use in playbooks that are specific to one type of server configuration/setup. The role works cross-platform, but I think the use case of having the same _playbook_ deploying to different OSes is a little more edge-case, but I'll leave this ticket open for anyone else to chime in for now.

I like making the role as flexible as possible, but generally roles are made cross platform, but the playbooks that use the roles are more platform and architecture-specific.

**Comment by sagikazarmark** [comment]
Hm, makes sense. Actually, I never thought about creating multiple playbooks for separate environments. One possible downside of that is probably common things cannot be shared between the two playbooks. At least I didn't find any reference for inclusion in playbooks.

**Comment by geerlingguy** [comment]
@sagikazarmark - Typically if there's more than one or two tasks that need to be the same in more than one playbook, it's best to create your own role that can have it's _own_ overridden variables, and then include that role in both playbooks.

Most of my playbooks go something like this:

```yaml
---
- hosts: example

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.mysql
    - accounts
    - companyxyz
```

And the `accounts` role has account setup info (for CI users, any admin groups, that kind of thing), and the `companyxyz` role would have specific server tweaks for that set of servers for that particular client/app (which could be platform-specific as well).

Then each server type gets its own playbook (like the above) with it's own vars file.

**Comment by sagikazarmark** [comment]
Is it possible to store role variables in that var file? Because I tried to store some variables in a var file, and they were not set in the role.

**Comment by AleksNovak** [comment]
Yes that’s what I usually do.
I extract all vars file that I can find into `vars/` to override with my own config:
```yaml
---
- name: Deploy GitLab
  hosts: gitlab
  vars_files:
  - vars/gitlab.yml
  pre_tasks:
  - include: tasks/gitlab_pre.yml
  post_tasks:
  - include: tasks/gitlab_post.yml
  roles:
  - ansible-role-repo-epel
  - ansible-role-ansible
  - ansible-role-gitlab
  tags:
  - gitlab
- name: Deploy HAProxy
  hosts: haproxy
  vars_files:
  - vars/haproxy.yml
  roles:
  - ansible-role-haproxy
```
