### ISSUE TITLE
Unsupported parameter 'column_case_sensitive' in mysql_user module

### ISSUE THREAD

**Issue by Diegiwg** [geerlingguy/ansible-role-mysql#564]
When running this role on version 5.0.0, the task `Ensure MySQL users are present` fails due to an unsupported parameter `column_case_sensitive` in the `mysql_user` module.

**Environment:**
- **Role Version:** 5.0.0
- **OS:** Ubuntu 24.04
- **Ansible Version:** core 2.16.14
- **MySQL Version:** 8.0

**Error Message:**

```javascript
TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************

failed: [ubuntu2404] (
   item={
      'name': 'devopness', 
      'host': '%', 
      'password': '***************', 
      'priv': 'devopness.*:ALL'
    }) => {
      "ansible_loop_var": "item", 
      "changed": false, 
      "item": {
            "host": "%", 
            "name": "devopness", 
            "password": "***************", 
            "priv": "devopness.*:ALL"
      },
      "msg": "Unsupported parameters for (mysql_user) module: column_case_sensitive. 
              Supported parameters include: append_privs, ca_cert, check_hostname, 
              check_implicit_admin, client_cert, client_key, config_file, 
              connect_timeout, encrypted, force_context, host, host_all, login_host,
              login_password, login_port, login_unix_socket, login_user, password,
              plugin, plugin_auth_string, plugin_hash_string, priv, resource_limits,
              session_vars, sql_log_bin, state, subtract_privs, tls_requires,
              update_password, user (name, ssl_ca, ssl_cert, ssl_key)."
      }
```

**Usage:**

```yaml
vars:
    _mysql_users:
      - name: "devopness"
        host: "%"
        password: "***************"
        priv: "devopness.*:ALL"

    _mysql_root_password: "***************"
    _mysql_databases:
      - name: "devopness"
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci

tasks:
    - name: mysql | LOG_LEVEL_MINIMAL - MySQL - Install
      ansible.builtin.include_role:
        name: geerlingguy.mysql
      vars:
        mysql_users: "{{ _mysql_users }}"
        mysql_root_password: "{{ _mysql_root_password }}"
        mysql_databases: "{{ _mysql_databases }}"
```
