### ISSUE TITLE
Ability to install the latest version MySQL

### ISSUE THREAD

**Issue by ArtemProkopenko** [geerlingguy/ansible-role-mysql#64]
Thank you for excellent Roles. 

It would be great if we could install the latest version (or at least 5.6) MySQL. 
- For Ubuntu 14.04 role installs 5.5.44

**Comment by mightydok** [comment]
Hi.
You can use this code for playbook to install latest MySQL version:
```yml
- name: Deploy MySQL servers and databases
  hosts: db
  become: yes
  pre_tasks:
  - name: Add MySQL repository key
    apt_key: url=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present

  - name: Add MySQL Server repository
    apt_repository: repo='deb http://repo.mysql.com/apt/debian/ jessie mysql-5.6' state=present

  - name: Add MySQL Python Connector repository
    apt_repository: repo='deb http://repo.mysql.com/apt/debian/ jessie connector-python-2.0' state=present

  roles:
  - geerlingguy.mysql
```
