### ISSUE TITLE
CentOS 7 MySQL installation.

### ISSUE THREAD

**Issue by prasann** [geerlingguy/ansible-role-mysql#73]
CentOS 7+ has mariadb database engine instead of mysql. I could see the steps to use this playbook to install MariaDB. 

Is it possible to install MySQL in CentOS 7+using this playbook?

**Comment by geerlingguy** [comment]
It is, but you would need to add the repository to install MySQL packages manually, maybe in `pre_tasks`, prior to running this role.

**Comment by abriel** [comment]
also you could set up role variables:
```
    mysql_packages:
    - mariadb
    - mariadb-server
    - mariadb-libs
    - MySQL-python
    - perl-DBD-MySQL
```

**Comment by pporada-gl** [comment]
@prasann 
I have a role whose sole purpose is to run
```
---
- name: Install the MySQL Community Edition repository
  shell: rpm -Uvh https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
  args:
    creates: /etc/yum.repos.d/mysql-community.repo
```

Then with the geerlingguy.mysql role, I can specify the following variables
```
mysql_enablerepo: "mysql55-community"
mysql_packages:
  - mysql-community-client
  - mysql-community-server
```
